global:
  scrape_interval: 15s

scrape_configs:
  - job_name: pawprints-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth:8000
          - event:8000
          - media:8000
          - analytics:8000
